name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      VITE_GIT_HOOKS: "0"
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - name: install
        run: vp install --frozen-lockfile --prefer-offline
      - name: check
        run: vp check
      - name: check testbed licenses
        run: vp run check:testbeds
      - name: audit
        if: ${{ !cancelled() }}
        run: vp pm audit
      - name: test
        if: ${{ !cancelled() }}
        run: vp run test:self
        env:
          COREPACK_ENABLE_STRICT: 0
